spring.application.name=platform
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/assoue_db
spring.datasource.username=assoue_user
spring.datasource.password=assoue_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration